volumes:
  postgres_master_data:
  postgres_replica_data:

services:
  web:
    image: ferkinkz/qyzmetapp.back:latest
    restart: always
    depends_on:
      - master_db
      - replica_db

  master_db:
    image: postgres:12-alpine
    volumes:
      - postgres_master_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qyzmetdb
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1

  replica_db:
    image: postgres:12-alpine
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qyzmetdb
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=password2
