volumes:
  static_data:
  postgres_master_data:
  postgres_replica_data:

services:
  web:
    image: ferkinkz/qyzmetapp.back:latest
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - master_db
      - replica_db
    volumes:
      - static_data:/code/qyzmetapp/static/
    environment:
      - DJANGO_SETTINGS_MODULE=qyzmetapp.settings.test

  master_db:
    image: postgres:12-alpine
    volumes:
      - postgres_master_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qyzmetdb
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1

  replica_db:
    image: postgres:12-alpine
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qyzmetdb
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=password2
