# Generated by Django 5.1.2 on 2025-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_userinstance_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstance',
            name='last_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
