# Generated by Django 5.1.2 on 2025-04-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_userinstance_last_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
